
import { Event, Category } from './types';

export const CATEGORIES: Category[] = ['All', 'Music', 'Tech', 'Sports', 'Art'];

export const EVENTS: Event[] = [
  {
    id: 1,
    title: 'Lahore Music Festival 2024',
    description: 'A spectacular celebration of Pakistani music and culture.',
    longDescription: 'Experience the rich musical heritage of Pakistan with performances by top artists including Atif Aslam, Ali Zafar, and emerging talents. Featuring traditional qawwali, modern pop, and fusion music. Enjoy delicious Pakistani cuisine and cultural exhibitions.',
    location: 'Lahore Fort, Punjab',
    date: '2024-10-26',
    time: '18:00 - 04:00',
    price: 2500.00,
    category: 'Music',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&h=400&fit=crop&crop=center',
    organizer: 'Pakistan Cultural Society',
    availableSeats: 5000,
  },
  {
    id: 2,
    title: 'Karachi Tech Summit 2024',
    description: 'Pakistan\'s premier technology and innovation conference.',
    longDescription: 'Join Pakistan\'s leading tech entrepreneurs, developers, and innovators for a comprehensive look at the future of technology. Featuring sessions on AI, blockchain, fintech, and startup ecosystem. Network with industry leaders and discover emerging opportunities.',
    location: 'Karachi Expo Centre, Sindh',
    date: '2024-11-15',
    time: '09:00 - 17:00',
    price: 15000.00,
    category: 'Tech',
    image: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=600&h=400&fit=crop&crop=center',
    organizer: 'Pakistan Software Houses Association',
    availableSeats: 1200,
  },
  {
    id: 3,
    title: 'Pakistan Super League (PSL) Final',
    description: 'Witness the ultimate cricket showdown in Pakistan\'s premier T20 league.',
    longDescription: 'Experience the electrifying atmosphere of PSL finals with world-class cricket action. Watch your favorite teams compete for the championship trophy. Enjoy live entertainment, food stalls, and meet-and-greets with cricket stars.',
    location: 'Gaddafi Stadium, Lahore',
    date: '2024-09-22',
    time: '19:00 - 23:00',
    price: 5000.00,
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=600&h=400&fit=crop&crop=center',
    organizer: 'Pakistan Cricket Board',
    availableSeats: 25000,
  },
  {
    id: 4,
    title: 'Lok Virsa Cultural Exhibition',
    description: 'A vibrant showcase of Pakistan\'s diverse cultural heritage.',
    longDescription: 'Immerse yourself in the rich tapestry of Pakistani culture through traditional crafts, folk music, dance performances, and art exhibitions. Experience the beauty of regional traditions from all four provinces. Interactive workshops and cultural demonstrations.',
    location: 'Lok Virsa Museum, Islamabad',
    date: '2024-12-05',
    time: '10:00 - 20:00',
    price: 1000.00,
    category: 'Art',
    image: 'culture.jpg',
    organizer: 'National Institute of Folk Heritage',
    availableSeats: 800,
  },
  {
    id: 5,
    title: 'Sufi Night at Shrine of Data Ganj Bakhsh',
    description: 'An enchanting evening of spiritual Sufi music and poetry.',
    longDescription: 'Experience the mystical world of Sufism with traditional qawwali performances by renowned artists. Held at the historic shrine, this spiritual gathering features soul-stirring music, poetry recitals, and a peaceful atmosphere for reflection and meditation.',
    location: 'Shrine of Data Ganj Bakhsh, Lahore',
    date: '2024-08-17',
    time: '19:30 - 22:00',
    price: 2000.00,
    category: 'Music',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=400&fit=crop&crop=center',
    organizer: 'Sufi Cultural Foundation',
    availableSeats: 1000,
  },
  {
    id: 6,
    title: 'Pakistan Startup Ecosystem Summit',
    description: 'Connecting entrepreneurs, investors, and innovators across Pakistan.',
    longDescription: 'Join Pakistan\'s thriving startup community for insights into funding, scaling, and building successful businesses. Featuring pitch competitions, investor panels, and networking sessions. Discover the latest trends in fintech, e-commerce, and digital innovation.',
    location: 'Arfa Karim Technology Park, Lahore',
    date: '2024-10-02',
    time: '09:00 - 18:00',
    price: 8000.00,
    category: 'Tech',
    image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=600&h=400&fit=crop&crop=center',
    organizer: 'Pakistan Startup Ecosystem',
    availableSeats: 1500,
  },
  {
    id: 7,
    title: 'Karachi Food Festival 2024',
    description: 'A culinary journey through Pakistan\'s diverse and delicious cuisine.',
    longDescription: 'Experience the rich flavors of Pakistan with over 100 food stalls featuring traditional dishes from all provinces. From spicy biryani to sweet jalebi, from street food to fine dining. Live cooking demonstrations, food competitions, and cultural performances. A paradise for food lovers!',
    location: 'Clifton Beach, Karachi',
    date: '2024-12-15',
    time: '10:00 - 22:00',
    price: 1500.00,
    category: 'Art',
    image: 'food.jpg',
    organizer: 'Karachi Food Society',
    availableSeats: 10000,
  },
  {
    id: 8,
    title: 'Pakistan International Film Festival',
    description: 'Celebrating Pakistani cinema and international films.',
    longDescription: 'A week-long celebration of Pakistani and international cinema featuring premieres, screenings, and filmmaker meet-and-greets. Showcasing the best of Pakistani films, documentaries, and short films. Panel discussions with industry experts, workshops for aspiring filmmakers, and awards ceremony.',
    location: 'Cinepax Cinema, Islamabad',
    date: '2024-11-20',
    time: '14:00 - 23:00',
    price: 3000.00,
    category: 'Art',
    image: 'film.jpg',
    organizer: 'Pakistan Film Institute',
    availableSeats: 2000,
  }
];
